// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIj42x-vJ_IpLi3i50M3-ECT_APxlfHw',
    appId: '1:599548577431:web:7661a58cf62478fd364bd2',
    messagingSenderId: '599548577431',
    projectId: 'gyroloop-fd0bc',
    authDomain: 'gyroloop-fd0bc.firebaseapp.com',
    storageBucket: 'gyroloop-fd0bc.appspot.com',
    measurementId: 'G-SSQR1F0SW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwtrJ3MzOOqcLv8BN2GpUVpsTDbX5gp2c',
    appId: '1:599548577431:android:c24725bfc8c456d2364bd2',
    messagingSenderId: '599548577431',
    projectId: 'gyroloop-fd0bc',
    storageBucket: 'gyroloop-fd0bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz87EznBN3BFYdkFZCrgduqF_JUNjRCx4',
    appId: '1:599548577431:ios:621f5add40914397364bd2',
    messagingSenderId: '599548577431',
    projectId: 'gyroloop-fd0bc',
    storageBucket: 'gyroloop-fd0bc.appspot.com',
    iosClientId:
        '599548577431-j4m4g2alqqjac0jelkg76o284rthjqa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gyroloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz87EznBN3BFYdkFZCrgduqF_JUNjRCx4',
    appId: '1:599548577431:ios:36cf9b6b71303782364bd2',
    messagingSenderId: '599548577431',
    projectId: 'gyroloop-fd0bc',
    storageBucket: 'gyroloop-fd0bc.appspot.com',
    iosClientId:
        '599548577431-956fgo4hkvk4okgkbv31dv6evje5eh0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.gyroloop.RunnerTests',
  );
}
